### ISSUE TITLE
Export Failure JPDB Export

### ISSUE THREAD

**Issue by tphLatte** [JaiWWW/JPDB-Export#9]
I tried to export a jpdb deck but my connection failed halfway through, and I had to reload the page. I tried to export it again and was immediately told that there is an export in progress and that multiple arent allowed.

**Comment by JaiWWW** [comment]
Hi kanjiTreeGirl, sorry for the inconvenience and for taking a while to reply!
It should be possible to fix this by pasting the following line of code at the top of the script (below line 17 to be safe):
`GM_setValue('workingURL', '')`
Then run the script by opening a new window and going to a deck (or refreshing a page with a deck open).
After this you'll need to remove the line and run the script once again, otherwise it won't be able to export multi-page decks.

I'll fix this next time I update the script, thanks for the report!

**Comment by JaiWWW** [comment]
Please feel free to reopen the issue if it doesn't work!
